name: Check a Pull Request's Quality

on:
  pull_request:
    branches: [ "master", "dev" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Check if code can be compiled
    env:
       GITHUB_USERNAME: ${{ github.actor }}
       GITHUB_TOKEN: ${{ secrets.OPTIMIZATION_TOKEN }}
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
       
     - name: Setup Java
       uses: actions/setup-java@v3
       with:
        distribution: corretto
        java-version: 8
        
     - name: Setup Gradle
       uses: gradle/gradle-build-action@v2
    
     - name: Execute Gradle build
       run: chmod +x gradlew ; ./gradlew compileJava